name: Unit Test

on: 
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clean Workspace
      run: ./gradlew clean 
    - name: Execute Unit Test  
      run: ./gradlew test -PfailFast=true -PignoreFailure=false
